pipeline {
    agent any
       environment {
    DOCKER_CREDENTIALS = 'DockerHubCredentials'
       }
    stages {
        stage('Clone Repository') {
            steps {
                git branch: 'main', url: 'https://github.com/PavanThumati/ecommercePageWithJenkins-Docker.git'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh 'docker build -t pavanthumati/ecommerce-backend:latest backend/'
            }
        }

       stage('Push to Docker Hub') {
    steps {
        script {
            withCredentials([usernamePassword(credentialsId: DOCKER_CREDENTIALS, passwordVariable: 'DOCKER_PASSWORD', usernameVariable: 'DOCKER_USERNAME')]) {
                // Login securely using --password-stdin
                sh 'echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin'

                    sh 'docker push pavanthumati/ecommerce-backend:latest'
                }
            }
        }
       }

        stage('Deploy') {
            steps {
                sh 'docker run -d -p 5000:5000 pavanthumati/ecommerce-backend:latest'
            }
        }
    }
}
